#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

bitcoind_network_traffic - Plugin to monitor the network traffic

=head1 CONFIGURATION

 [bitcoind*]
    user bitcoin
    env.binary bitcoin-cli
    env.data_dir /mnt/data/bitcoin
    env.conf_dir /home/bitcoin/.bitcoin

=head1 AUTHOR

Cedric Felizard

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/bitcoin-cli"}
CONF_DIR=${conf_dir:-"/var/lib/bitcoin"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Network traffic'
    echo 'graph_vlabel bytes'
    echo 'graph_category bitcoind'
    echo 'graph_info This graph shows the sum of incoming and outgoing traffic.'
    echo 'bitcoind_network_traffic_in.label Net traffic in'
    echo 'bitcoind_network_traffic_in.info Incoming network traffic.'
    echo 'bitcoind_network_traffic_out.label Net traffic out'
    echo 'bitcoind_network_traffic_out.info Outgoing network traffic.'
    echo 'bitcoind_network_traffic_total.label Net traffic total'
    echo 'bitcoind_network_traffic_total.info Total network traffic.'
    exit 0
fi

STATS="$($BINARY -datadir=$CONF_DIR getnettotals)"
echo "bitcoind_network_traffic_in.value $(echo "$STATS" | grep totalbytesrecv | grep -o '[0-9]*')"
echo "bitcoind_network_traffic_out.value $(echo "$STATS" | grep totalbytessent | grep -o '[0-9]*')"
echo "bitcoind_network_traffic_total.value $(echo "$STATS" | grep totalbytes | grep -o '[0-9]*' | sed "N;s/\n/+/" | bc)"
