#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

bitcoind_difficulty - Plugin to monitor the current blockchain difficulty

=head1 CONFIGURATION

 [bitcoind*]
    user bitcoin
    env.binary bitcoin-cli
    env.data_dir /mnt/data/bitcoin
    env.conf_dir /home/bitcoin/.bitcoin

=head1 AUTHOR

Cedric Felizard
kakobrekla

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/bitcoin-cli"}
CONF_DIR=${conf_dir:-"/var/lib/bitcoin"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Difficulty'
    echo 'graph_vlabel Difficulty'
    echo 'graph_category bitcoind'
    echo 'graph_info This graph shows the current blockchain difficulty.'
    echo 'bitcoind_difficulty.label Difficulty'
    echo 'bitcoind_difficulty.info The current difficulty.'
    exit 0
fi

echo "bitcoind_difficulty.value $($BINARY -datadir=$CONF_DIR getdifficulty)"
